### ISSUE TITLE
isTiledMap fail on Maps with Animations

### ISSUE THREAD

**Issue by Lurkars** [workadventure/tiled-map-type-guard#3]
For me, maps with animated tiles fail. I think the error is about "isTiledMapTile" where `animation: isTiledMapFrame,` expects single TiledMapFrame. Instead it should be `animation: tg.isArray(isTiledMapFrame),`

**Comment by moufmouf** [comment]
Thanks @Lurkars .

This should be fixed. Github actions is down right now so we will have to wait for it to be back up to have a properly tagged release.
